### ISSUE TITLE
PLG_JTG_MAPS_CANT_RENDER_TRACKS

### ISSUE THREAD

**Issue by ymestechwey** [mastervanleeuwen/J-TrackGallery#22]
Hello,

When i'm trying to show the map on the front page, i get the error: PLG_JTG_MAPS_CANT_RENDER_TRACKS
Doesn't matter which track i use.

This is the code i use: {JTRACKGALLERYMAP}id=48 show_link=true{/JTRACKGALLERYMAP}

Do you know how i can solve this?

**Comment by mastervanleeuwen** [comment]
Hi,
Could you try using a comma between the arguments, i.e.:
`{JTRACKGALLERYMAP}id=48,show_link=true{/JTRACKGALLERYMAP}`

If that does not work, could you try updating to the most recent versions of the module and plugins from this page:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc5

Please let me know whether this solves your problem or if the problem persists.

**Comment by ymestechwey** [comment]
Hello,

I updated the module en plugin, it still shows me that it's version 0.9.33

<img width="938" alt="Screenshot 2022-06-03 at 13 45 51" src="https://user-images.githubusercontent.com/55656260/171847965-bde24e50-dce6-4fda-ad5c-4ec85c960c65.png">
<img width="762" alt="Screenshot 2022-06-03 at 13 51 52" src="https://user-images.githubusercontent.com/55656260/171848332-75d35f57-5758-4420-a345-ef05cd506213.png">


<br />
<br />
Also i changed the arguments but that didn't solve the issue either:

<img width="789" alt="Screenshot 2022-06-03 at 13 45 59" src="https://user-images.githubusercontent.com/55656260/171847960-fffacd32-cfd5-4478-942f-ff48f7e3ef0c.png">

**Comment by mastervanleeuwen** [comment]
Hi,

Do you use the plugin more than once on the same page? I (re-)checked the code, and this error message shows up when you try to show more than one map on a single page, which is currently not supported. The error message is rather cryptic, because the translation files were not properly installed; I have fixed this in my local test version.

On a side note, I tried to look at your website, and noticed that the main overview page:
https://mbbn.nl/twente/index.php/activiteiten/route-s
shows an error message: Call to undefined method GpsDataClass::writeOLMap()
which suggests that you have an incomplete update of the module code.
This function call used to exist in the code, but I changed some of the internal working and it no longer exists; all of the code was updated to call the new functions (in the helper/maphelper.php file), so I am surprised to see this error. Let me know if you need further help/hints to try and fix this.

**Comment by mastervanleeuwen** [comment]
Hi,

There is a new release on the release page:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34

which has the new version of the plugin that has clearer warnings and also supports showing more than one map on a single page, like shown here: https://testing.gta-trek.eu/index.php/en/plugin

Please give it a try and don't hesitate to ask in case something is not working.

**Comment by ymestechwey** [comment]
Im gonna test it in a couple of days. Thank you

**Comment by cogulobi** [comment]
Hi Marco, 
your page shows correctly in my browser.

In my page I see:
<link href="leviedellatransumanza4media/com_jtg/js/openlayers/ol.css" rel="stylesheet" />
<link href="leviedellatransumanza4media/com_jtg/js/openlayers/ol.css.map" rel="stylesheet" />

I think that a "/" is missing before "media/com"

Best regards,
Corrado

**Comment by cogulobi** [comment]
Thank you Marco, I confirm that for me the problem is solved.
