### ISSUE TITLE
Some tracks are not showing

### ISSUE THREAD

**Issue by cogulobi** [mastervanleeuwen/J-TrackGallery#26]
Hi Marco,
some tracks are not showing on the map. More precisely, I see them on the overview map, but if I want to see them in detail, I do not obtain the map view. Speed, altitude, and the other data show correctly, but the map view is missing. I think it is a problem of the gpx file. Probably something related to waypoints...
I'm sending you one of the files which do not show. Can you individuate the problem?

Thank you!

Best regards,
Corrado

[SantAgataDiPuglia-Candela.gpx.zip](https://github.com/mastervanleeuwen/J-TrackGallery/files/9109739/SantAgataDiPuglia-Candela.gpx.zip)

**Comment by mastervanleeuwen** [comment]
Hi Corrado,

Thanks for spotting this issue and providing the test file. It turns out that the problem was that there was a single quote, ', in the track title. I have fixed the code so that this is properly displayed, see my text page here:
https://testing.gta-trek.eu/index.php/nl/j-trackgallery/track/18

The version with this improvement is available at this page: 
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc12

Best regards, Marco.

**Comment by DavidJRichards** [comment]
Greetings Marco, Adding a title containing a single quote to a gallery picture also prevents the track map from being displayed. I've learnt not to do this now, my Blacksmith's shop photo caught me out. Kind regards, David.

**Comment by mastervanleeuwen** [comment]
Hi David,

Thanks for the report. This was easy to fix. I have included a patch for this issue in the latest pre-release version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc13

Best regards, Marco.

**Comment by cogulobi** [comment]
Hi Marco,
your patch solved the problem.
Thank you.

Best regards,
Corrado
