### ISSUE TITLE
Hidden fiel is ignored

### ISSUE THREAD

**Issue by cogulobi** [mastervanleeuwen/J-TrackGallery#29]
Hi Marco,
in the past, when the "hidden" flag of a track was set, I was still able to show the track in the plugins, but the same was missing from the track list and from the overview map. That behavior was perfect for my purposes.
Currently, it seems that the hidden flag is ignored and tracks always appear in the track list and in the overview map. 
Is it possible to restore previous behavior?
Best regards,
Corrado

**Comment by mastervanleeuwen** [comment]
Hi Corrado,

Thanks for the report. I tried this out on my test site, and it seems to work for me: 'hidden' files are not shown both in the list view and in the overview map. Could it be that you were logged in to the site front end when you tested this? When you are logged in, it will show all the tracks that you own, including hidden and non-public ones, plus the non-hidden and public from other users.

Please let me know if the problem persists or if I misunderstood; I can then still have a closer look at the code...

Best regards, Marco.

**Comment by cogulobi** [comment]
Hi Marco,
the problem persists even if I'm not logged in. 
I noticed the presence of tab "My tracks" I did not notice in the past. Is it new? However, if I click on that  tab I get an error page with written "0 Call to a member function getDbo() on null". It is not relevant if I'm logged or not.

Best regards,
Corrado

**Comment by mastervanleeuwen** [comment]
Dear Corrado,

I see; this is unexpected; the 'My Tracks' menu item only appears when you are logged it. That page is currently not working due to a small typo, which I will fix. However, the fact that the My Tracks item is shown, suggests that you stay logged in. I tried it on my Joomla test server and there the behaviour is as expected. Maybe there is a problem with the 'log out' button on your system? This aspect is managed by the Joomla system itself and I would not know what to do in the J!TrackGallery code to change/improve the behaviour. Could you have a look at the 'users' -> manage tab in the adminstrator view? Under 'last visit' I think it shows the time that you last logged in or out. Could check that this time is updated when you log out of the frontend?

Best regards, Marco.

**Comment by cogulobi** [comment]
Hi Marco,
you were right. The user was automatically logged in by a cookie (I did not know it was possible to obtain such behavior) saved by the browser. Once I deleted the cookie, your page started working as expected. 
Sorry for the false alarm.
Corrado
