### ISSUE TITLE
System output

### ISSUE THREAD

**Issue by stay4you** [mastervanleeuwen/J-TrackGallery#36]
Hi
First thank you for a great extension, I have been using it now for some time with no issues but since upgrading to Joomla 4 when clicking on the links to select a track the extension opens within the output of my home page setup, allthough the url is correct for the track the title remains as per the home page as does the layout, I have checked the modules are not set to any j-track menus. I have tried changing the teplate but still the same, I am not sure if the is an issue with j-track or my setup, but as all my other extensions are rendering ok I thought I would ask if you can advise.

    Regards
      Gary

**Comment by mastervanleeuwen** [comment]
Hi Gary,

That is indeed strange; I would need a little more details to debug this. Before starting that, could you try installing the latest version from here:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc22
This contains a number of small changes and fixes. I don't expect that they will affect the behaviour that you observe, but it is worth trying.

I tried looking at your website: https://www.stay4you.com/guide/tracks-routes/category-list/cats
but it seems that none of the J-trackgallery pages are working at the moment. The error message:
`0: Call to undefined method Joomla\CMS\Application\SiteApplication::isAdmin()`
could be caused by a call in the J-TrackGallery code, but it is in a part of the code that is not used anymore, as far as I know. I also do not get this error on my test web site. Which version of Joomla 4 are you using?

Best regards, Marco.

**Comment by stay4you** [comment]
Hi Marco
I am using 4.2.6 The links from my menu to j-trackgallery are now working the problem seemed to be from an update from sh404sef to 4sef but the j-trackgallery internal links still opening within the output of my home page, also the add track form at https://www.stay4you.com/guide/tracks-routes/login-gps/add-track/track/form reports "Unable to display an editor because no editor plugin is published" but the editor plugin is enabled.

**Comment by mastervanleeuwen** [comment]
Hi Gary,

Thanks for bringing this up; it took me some time to understand what is happening, but I think I managed to improve the behaviour of the templates for the J-Trackgallery pages. Could you try the new version from here:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/download/0.9.34-rc25/com_jtg.zip

and let me know whether that improves the behaviour.

I have not yet looked in to the editor error; I will look into that soon.

Best regards, Marco.

**Comment by stay4you** [comment]
Hi
Once again a great job thanks for that.

Regards
    Gary

**Comment by mastervanleeuwen** [comment]
Hi Gary,

Concerning the error with the editor: 

> also the add track form at https://www.stay4you.com/guide/tracks-routes/login-gps/add-track/track/form reports "Unable to display an editor because no editor plugin is published" but the editor plugin is enabled.

This seems to be more of a Joomla setting. I search a bit on Google and found that there is both a general setting and a per-user setting. Could you check the user-specific setting by going to Users->Manage in the backend and clicking a specific user, and then look in this tab:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/23643853/212368101-ff00d0d8-0672-45ca-a049-ce99a67c82ef.png">

to check that 'Editor' is set to '-Use default-' or to a specific editor?

Best regards, Marco.
