### ISSUE TITLE
Front end language overrides

### ISSUE THREAD

**Issue by noelada** [mastervanleeuwen/J-TrackGallery#46]
Hi Marco,
In the back end TRANSLATIONS, I added a change to Terrain:
				; These are additional translation strings added by users
; Used in Front-end AND Back-end

COM_JTG_CAT_CAR_44="Car 4*4"
COM_JTG_TERRAIN="Locality"

This works in the back end, but the front end is still showing "Terrain" from en-GB.com_jtg_common in ROOT/Language/en-GB

Also the new feature to disable difficulty does not work for me (I selected No from Use dropdown in Configuration/Difficulty Level). Disable Category works fine.
Regards,
Noel.

**Comment by mastervanleeuwen** [comment]
Hi Noel,

Thanks for the reports.

The issue with the language overrides was due to a typo in the code. This is fixed in this release: 

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc27

Concerning the difficulty setting: this was not yet applied in the plugin, I have now updated the plugin to also respect this setting (as well as the 'use category' setting). Note that you can still set the difficulty when uploading the track. I could also remove it there, but the database still has the field, so I initially thought it would better to keep it accessible.

Best regards, Marco.

**Comment by noelada** [comment]
Thanks Marco,

Another problem I noticed is that the delete track does not work from front end. It works fine from back end.

Regards,

Noel.

**Comment by mastervanleeuwen** [comment]
Dear Noel,

Thanks for the report; this was a side-effect of the changes to the router that I made. I implemented a fix and released a new version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc28

Best regards, Marco.

**Comment by noelada** [comment]
Thank Marco,

Delete now works thank you.

Regards,

Noel.

**Comment by noelada** [comment]
Thanks Marco,
We have it installed in our main site now and are getting excellent reports from users.
Cheers,
Noel.
