### ISSUE TITLE
Jtrackgallerymaps plugin does not suppress speed chart when speed chart hidden in menu options

### ISSUE THREAD

**Issue by noelada** [mastervanleeuwen/J-TrackGallery#58]
Hi Marco,
The configuration option speed cart hide works everywhere except in the plugin. I have made it work in the plugin by changing line 307 of jtrackgallery_maps.php to:
$graphJS = JtgMapHelper::parseGraphJS($gpsData, $cfg, $params, $usepace, $params->get("jtg_param_show_speedchart")/* true shows speed */, $graphid);
There may be better ways of fixing this issue? Could you please update the plugin, so the hide option works.
Thanks,
Noel.
![speed](https://github.com/mastervanleeuwen/J-TrackGallery/assets/121601487/6a073e60-aeb8-45f5-921a-d5ff0db978bc)

**Comment by mastervanleeuwen** [comment]
Hi Noel,

Thanks for the report and the suggestion. I have implemented a fix here: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc33
Please update both the com_jtg component and the plugin to make this work; I decided to make a change in the base code as well.

Your analysis of the issue is correct; the way that I had implemented the plugin, it would show all graphs when you selected the 'show_graph' option, instead of showing only the ones that are selected in the settings. 
I decided to fix this in a slightly more invasive way by removing the 'showgraph' argument from the makeGraphJS function (in maphelper.php), since it is no longer needed.

Best regards, Marco.

**Comment by noelada** [comment]
Hi Marco,

Thank you for the fix. All working well.

Best wishes,

Noel.
