### ISSUE TITLE
Menus reordering and renaming - small tips

### ISSUE THREAD

**Issue by joomleb** [mastervanleeuwen/J-TrackGallery#6]
Hi guys, 
to match menus and have them in the same way > I add an image for you
![jTrack-menus](https://user-images.githubusercontent.com/14607633/123851930-5ded3500-d8e1-11eb-8bee-e589c8de2a30.jpg)

**Comment by mastervanleeuwen** [comment]
Dear joomleb,

Thanks for the suggestion; this is now fixed/improved in the current development version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.32-rc3

I would have liked to also use the same language strings for both, but since the two menus are configured in different parts of the code, it seems that that is not immediately possible; I'll keep that on the to-do list.

Best regards, Marco.
